version = 0.1

[default.build.parameters]
beta_features = true
cached = false
use_container = false

[default.deploy.parameters]
stack_name = "{{STACK_NAME}}"
resolve_s3 = true
s3_prefix = "{{STACK_NAME}}"
region = "{{REGION}}"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = false
fail_on_empty_changeset = false
parameter_overrides = [
  "DatabaseUrl={{DATABASE_URL}}",
  "EnvironmentName={{ENVIRONMENT_NAME}}",
  "DomainHostedZoneId={{DOMAIN_HOSTED_ZONE_ID}}",
  "DomainName={{DOMAIN_NAME}}"
]

[default.global.parameters]
region = "{{REGION}}"
