#!/usr/bin/env node
/**
 * Build importable GRN crop catalog seed files from OpenFarm's public crops.csv.
 *
 * Source: https://raw.githubusercontent.com/openfarmcc/OpenFarm/mainline/lib/crops.csv
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE_URL =
  "https://raw.githubusercontent.com/openfarmcc/OpenFarm/mainline/lib/crops.csv";
const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const OUT_DIR = join(ROOT, "data", "catalog");
const OUT_JSONL = join(OUT_DIR, "openfarm_crops_import.jsonl");
const OUT_SQL = join(OUT_DIR, "openfarm_crops_seed.sql");
const OUT_META = join(OUT_DIR, "openfarm_crops_source_notes.md");
const MAX_RECORDS = 2000;

function slugify(value) {
  return value
    .trim()
    .toLowerCase()
    .replace(/\(.*?\)/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 96);
}

function sqlQuote(value) {
  if (value == null) return "NULL";
  return "'" + value.replace(/'/g, "''") + "'";
}

/** Minimal CSV line parser (handles quoted fields). */
function parseCsvLines(text) {
  const rows = [];
  for (const raw of text.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const fields = [];
    let i = 0;
    while (i < line.length) {
      if (line[i] === '"') {
        let end = i + 1;
        while (end < line.length) {
          if (line[end] === '"') {
            if (end + 1 < line.length && line[end + 1] === '"') {
              end += 2;
            } else {
              break;
            }
          } else {
            end++;
          }
        }
        fields.push(line.slice(i + 1, end).replace(/""/g, '"'));
        i = end + 2; // skip closing quote + comma
      } else {
        const next = line.indexOf(",", i);
        if (next === -1) {
          fields.push(line.slice(i));
          break;
        }
        fields.push(line.slice(i, next));
        i = next + 1;
      }
    }
    rows.push(fields);
  }
  return rows;
}

async function fetchCsvLines() {
  const resp = await fetch(SOURCE_URL, {
    headers: { "User-Agent": "GRN-Catalog-Builder/1.0" },
    signal: AbortSignal.timeout(60_000),
  });
  if (!resp.ok) throw new Error(`HTTP ${resp.status} fetching CSV`);
  const body = await resp.text();
  return parseCsvLines(body);
}

function normalizeRows(rows) {
  const dedupe = new Map();

  for (const row of rows) {
    if (!row.length) continue;
    const scientific = (row[0] ?? "").trim();
    const common = (row[1] ?? "").trim();

    if (!scientific || scientific.startsWith("?")) continue;
    if (!common) continue;
    if (!scientific.includes(" ")) continue;

    const slug = slugify(common || scientific);
    if (!slug || dedupe.has(slug)) continue;

    dedupe.set(slug, {
      slug,
      common_name: common || scientific,
      scientific_name: scientific,
      category: null,
      description: null,
      source: "openfarmcc/openfarm",
      source_id: scientific,
      source_url: SOURCE_URL,
      attribution: "OpenFarm community dataset (GitHub archive)",
    });
  }

  return [...dedupe.values()]
    .sort((a, b) => a.slug.localeCompare(b.slug))
    .slice(0, MAX_RECORDS);
}

function writeJsonl(records) {
  const content = records.map((r) => JSON.stringify(r)).join("\n") + "\n";
  writeFileSync(OUT_JSONL, content, "utf-8");
}

function writeSql(records) {
  const lines = [
    "-- Generated by scripts/catalog/build_openfarm_seed.mjs",
    `-- Source: ${SOURCE_URL}`,
    "begin;",
  ];

  for (const r of records) {
    lines.push(
      "insert into crops (slug, common_name, scientific_name, category, description)",
      `values (${[
        sqlQuote(r.slug),
        sqlQuote(r.common_name),
        sqlQuote(r.scientific_name),
        sqlQuote(r.category),
        sqlQuote(r.description),
      ].join(", ")})`,
      "on conflict (slug) do update set",
      "  common_name = excluded.common_name,",
      "  scientific_name = excluded.scientific_name,",
      "  category = excluded.category,",
      "  description = excluded.description,",
      "  updated_at = now();",
      ""
    );
  }

  lines.push("commit;");
  writeFileSync(OUT_SQL, lines.join("\n"), "utf-8");
}

function writeMeta(records) {
  const content = [
    "# OpenFarm Crop Source Notes",
    "",
    `- Source URL: \`${SOURCE_URL}\``,
    "- Upstream project: https://github.com/openfarmcc/OpenFarm",
    "- Retrieval mode: public GitHub raw file download",
    `- Records generated: **${records.length}**`,
    "",
    "## Attribution",
    "Use attribution text in-product/docs:",
    "",
    "`Plant names sourced from the OpenFarm community dataset (openfarmcc/OpenFarm archive).`",
    "",
    "## Licensing / usage note",
    "This file should be treated as source research output; confirm data licensing expectations before public redistribution beyond GRN app usage.",
  ].join("\n");
  writeFileSync(OUT_META, content, "utf-8");
}

async function main() {
  mkdirSync(OUT_DIR, { recursive: true });
  const rows = await fetchCsvLines();
  const records = normalizeRows(rows);
  writeJsonl(records);
  writeSql(records);
  writeMeta(records);
  console.log(`Generated ${records.length} records`);
  console.log(OUT_JSONL);
  console.log(OUT_SQL);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
